### ISSUE TITLE
Figure out the correct license, or selection of licenses, to use

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#12]
MIT, gnu, ...?

**Comment by drewoldag** [comment]
We'll need to update the Copier prompts to show the various supported licenses, and have a reasonable default license selected as well. We'll also need to introduce a little more logic in the templates so that we can produce the correct license file based on the users response.

**Comment by drewoldag** [comment]
We can use the `choices` key for the question section to allow the user to pick the right license. Will probably need to chat with Andy or Mario to determine what licenses should be included. 

In this section of the `copier` readthedocs, (https://copier.readthedocs.io/en/latest/configuring/#advanced-prompt-formatting), the second example snippet includes this question, which is very close to what we want. It would be nice though to just have the text of the license in a file, instead of hardcoded in the copier.yml file. 

From example `copier.yml`
```
project_license:
    # User will see only the dict key and choose one, but you will
    # get the dict value in your template
    choices:
        MIT: &mit_text |
            Here I can write the full text of the MIT license.
            This will be a long text, shortened here for example purposes.
        Apache2: |
            Full text of Apache2 license.
    # When using choices, the default value is the value, **not** the key;
    # that's why I'm using the YAML anchor declared above to avoid retyping the
    # whole license
    default: *mit_text
    # You can still define the type, to make sure answers that come from --data
    # CLI argument match the type that your template expects
    type: str
```

We might be able to use conditional rendering of files like shown here (https://copier.readthedocs.io/en/latest/configuring/#conditional-files-and-directories) to avoid having to hardcode the text of the licenses in `copier.yml`.
