### ISSUE TITLE
Update pre-commit hook names to be more understandable.

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#164]
Currently some of the pre-commit hook names look like file names. For instance:
```
- repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        description: Clear output from Jupyter notebooks.
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --clear-output
```

Here `name` is just used to print out a message on the screen when pre-commit is running. It should be something like "Clear juypter notebook output" instead of "jupyter-nb-clear-output".
