### ISSUE TITLE
pre-commit: Configure isort with "black" profile when using black

### ISSUE THREAD

**Issue by carlosgjs** [lincc-frameworks/python-project-template#192]
isort and black can fight each other, so I found I had to add this to my `pyproject.toml`:

```
[tool.isort]
profile = "black"
```

**Comment by lsetiawan** [comment]
I have this in my `.pre-commit-config.yaml` under isort:

```
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
```

Pretty much doing the same thing, but probably cleaner to use the `pyproject.toml` setting
