### ISSUE TITLE
Add `workflow_dispatch` execution option to smoke test

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#271]
Useful to re-run the smoke test workflow on-demand in the github UI.

Add with something like:

```
on:
  schedule:
    - cron: 45 6 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
```
