### ISSUE TITLE
[metadata] is not allowed in pyproject.toml

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#328]
`pyproject.toml` tempalte has a `[metadata]` section, which is not a part of the specification. I met this issue when tried to make my first commit and `pre-commit`'s `validate-pyproject` failed on that.

Currently, this `[metadata]` has two fields: `long_description` and `url`.

I believe that `long_description` has never been used with `pyproject.toml` (it was used with `setup.py` and `setup.cfg` previously), and `project.readme` is enough for modern packaging. So `long_description` could be removed safely.

I think, that `url` was also never used with `pyproject.toml`. Currently, we should use `project.urls` instead:
```toml
[project.urls]
"Source Code" = "https://github.com/lincc-frameworks/python-project-template/"
"Documentation" = "https://lincc-ppt.readthedocs.io"
```
