### ISSUE TITLE
code_style.yaml may be invalid

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#377]
In current `main`, code_style.yaml may miss some newlines. Probably it is due to overuse of `{%-`.

My example, please note double `run` in `name: Install dependencies` and ` if [ -f requirements.txt ] ... - name: Analyze code with mypy` line:
```yaml
# This workflow will install Python dependencies, then perform static analysis for code style and type checking.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Style analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi- name: Analyze code with mypy
      run: |
        mypy ./src ./tests --ignore-missing-imports
    - name: Analyze code with ruff
       ruff format --check
       ruff check
```

My answers:
```yaml
# Changes here will be overwritten by Copier
_commit: v1.4.6-38-gc8eefc6
_src_path: gh:lincc-frameworks/python-project-template
author_email: hombit@gmail.com
author_name: LINCC Frameworks
create_example_module: true
custom_install: true
enforce_style:
- ruff
failure_notification:
- email
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: basic
package_name: pandas_ts
project_license: MIT
project_name: pandas-ts
project_organization: lincc-frameworks
python_versions:
- '3.9'
- '3.10'
- '3.11'
- '3.12'
```

Git blamed @delucchi-cmu, so you are assigned to it
