### ISSUE TITLE
Redundant isort and black configuration

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#453]
If I do not select `isort` and/or `black` with copier, I still have its configuration in `pyproject.toml`

```toml
[tool.black]
line-length = 110
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 110
```
